### PR TITLE
Fix scroll capture

### LINKED ISSUE #520: Zooming on heatmap should not scroll page

### PR DESCRIPTION
**Pull request by axelboc**
Fix #520

### CODE REVIEW

File: src/h5web/vis-packs/core/shared/PanZoomMesh.tsx [hunk 1]
```diff
@@ -94,16 +93,13 @@ function PanZoomMesh() {
...
-  const wheelCaptureRef = useWheelCapture();
+  useWheelCapture();
 
   return (
-    <>
-      <mesh {...{ onPointerMove, onPointerUp, onPointerDown, onWheel }}>
-        <meshBasicMaterial opacity={0} transparent />
-        <planeGeometry args={[width, height]} />
-      </mesh>
-      <Html ref={wheelCaptureRef} />
```
Comment (axelboc) [inline src/h5web/vis-packs/core/shared/PanZoomMesh.tsx:105]: It stopped working because of the `pointer-events: none` set on the root DOM element rendered by the `Html` compoent. Now, I hook straight onto the canvas' `domElement`, so we no longer need an `Html` element here!

**Review by loichuder — APPROVED** [review]
Great fix :slightly_smiling_face:
