### PR TITLE
Fetch int-64 values from h5grove as binary to maintain precision

### LINKED ISSUE #1679: 64-bit integers not shown correctly in h5web display
### Describe the bug

64-bit signed and unsigned integers are not always displayed correctly in the h5web display window.

### To Reproduce

1. Go to https://h5web.panosc.eu/h5grove?file=sample.h5
2. Select the `int64_scalar` dataset
3. Select `Display` view on the right panel
4. Value shown is: `-9223372036854776000`

### Expected behaviour

The value returned by `h5dump -d int64_scalar sample.h5` is: `-9223372036854775808`

Similar happens with uint64:
uint64_scalar datatype as shown on h5web window: `18446744073709552000`
while h5dump reports: `18446744073709551615`

### Context

- OS: Linux
- Browser: Firefox
- Version: 127.0
- H5Web context: h5web

### PR DESCRIPTION
**Pull request by axelboc**
Follows #1745 and closes #1679

### CODE REVIEW

File: packages/app/src/providers/utils.ts [hunk 1]
```diff
@@ -33,7 +36,7 @@ export function typedArrayFromDType(
         return Int16Array;
       case 32:
         return Int32Array;
-      case 64: // No support for 64-bit integer values in JS
+      case 64:
         return undefined;
```
Comment (loichuder) [inline packages/app/src/providers/utils.ts:40]: Why not returning `BigInt64Array` here ?

Comment (axelboc) [reply packages/app/src/providers/utils.ts:40]: Sorry, should have explained: for the same reason I have a separate type union, a separate type guard, etc. — when both kinds of typed arrays are mixed together in a union, TypeScript goes wild:

- You can't invoke the `Big(U)Int64Array` constructors with `number[]`, only with `bigint[]` (so `new IntOrBigIntTypedArray(arr as number [] | bigint[])` doesn't type-check)
- You can't loop through the array, since `number[]` and `bigint[]` aren't compatible.

Having a single function worked fine in `h5grove-api` since we invoke the typed array constructor with a buffer. However, it failed in `useIgnoreFillValue`, where we pass a `number`:

```ts
  const DTypedArray = typedArrayFromDType(dataset.type);

  // Cast fillValue in the type of the dataset values to be able to use `===` for the comparison
  const fillValue =
    DTypedArray && typeof wrappedFillValue[0] === 'number'
      ? new DTypedArray(wrappedFillValue as number[])[0]
      : undefined;
```

Arguably, perhaps `useIgnoreValue` should be reworked to support bigints as well... Seemed like a can of worms, though, so I went with a compromise.

Comment (loichuder) [reply packages/app/src/providers/utils.ts:40]: Yeah, ok I see.

**Review by loichuder — APPROVED** [review]
